### ISSUE TITLE
Fail on Mac OS X with "unhandled error event"

### ISSUE THREAD

**Issue by arun-gupta** [logentries/docker-logentries#39]
Trying to redirect Docker stats to LogEntries as:

`docker run logentries/docker-logentries -t 8cd5c40d-a2ac-4178-8850-cc57f95cb260 -a host="192.168.99.100"`

and getting the error:

`events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ENOENT
    at exports._errnoException (util.js:746:11)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)`

Wondering if its related to #36

**Comment by richmondwang** [comment]
@arun-gupta did you happen to solve this issue? mind sharing some insight? :)

**Comment by arun-gupta** [comment]
@richmondwang didn't try it again. I'd expect somebody from logentries team to provide a workaround.
